// Each application should include its required CRC algorithms here

// CRC-8 algorithms

#include "./algorithms/crc8_koopman.inc"
#include "./algorithms/crc8_nguyen.inc"

// CRC-12 algorithms

#include "./algorithms/crc12_umts.inc"

// CRC-16 algorithms

#include "./algorithms/crc16_ibm3740.inc"
#include "./algorithms/crc16_mcrfxx.inc"
#include "./algorithms/crc16_modbus.inc"
#include "./algorithms/crc16_nguyen.inc"

#include "./algorithms/crc16_fast.inc"

#include "./algorithms/crc16_ibm3740_offset.inc"

// CRC-32 algorithms

#include "./algorithms/crc32_hdlc.inc"

#include "./algorithms/crc32_hdlc_offset.inc"

// CRC-64 algorithms

#include "./algorithms/crc64_xz.inc"
