///////////////////////////////////////////////////////////////////////////////
//
// Algorithms that use Nguyen's Fast-CRC algorithms
//

#include "crc_algorithms/fast/crc8_fast4.inc"
#include "crc_algorithms/fast/crc16_fast4.inc"
#include "crc_algorithms/fast/crc24_fast4.inc"

#include "crc_algorithms/fast/crc16_fast6.inc"
#include "crc_algorithms/fast/crc24_fast6.inc"
#include "crc_algorithms/fast/crc32_fast6.inc"
#include "crc_algorithms/fast/crc64_fast6.inc"
