#undef USE_CRC_KERNEL_TABLE8

// Searchable on autosar.org

#include "crc_algorithms/standard/crc8_autosar.inc"
#include "crc_algorithms/standard/crc8_sae_j1850.inc"
#include "crc_algorithms/standard/crc16_arc.inc"
#include "crc_algorithms/standard/crc16_ibm_3740.inc"
#include "crc_algorithms/standard/crc32_autosar.inc"
#include "crc_algorithms/standard/crc32_iso_hdlc.inc"
#include "crc_algorithms/standard/crc64_xz.inc"

