#!/usr/bin/env bash

set -e

SCRIPT_PATH="${0%/*}"
REPO_ROOT="$(git rev-parse --show-toplevel)"

###############################################################################

function main()
{
  mkdir -p "${REPO_ROOT}/build/bin"

  gcc -o "${REPO_ROOT}/build/bin/crc.c.o" \
    -Wall -Wpedantic -std=c99 -fdiagnostics-color=always \
    -I "${REPO_ROOT}" \
    -I "${REPO_ROOT}/test" \
    \
    -c \
    "${REPO_ROOT}/crc.c" \
    \
    -L "${REPO_ROOT}"

  g++ -o "${REPO_ROOT}/build/bin/test_crc.cpp.o" \
    -Wall -Wpedantic -std=c++23 -fdiagnostics-color=always \
    -I "${REPO_ROOT}" \
    -I "${REPO_ROOT}/test" \
    \
    -c \
    "${REPO_ROOT}/test/test_crc.cpp" \
    \
    -L "${REPO_ROOT}"

  g++ -o "${REPO_ROOT}/build/bin/test_crc" \
         "${REPO_ROOT}/build/bin/crc.c.o" \
         "${REPO_ROOT}/build/bin/test_crc.cpp.o" \
         && "${REPO_ROOT}/build/bin/test_crc"
}

###############################################################################

main "$@"
