#!/usr/bin/env bash

set -e

###############################################################################

function find_tmp_dir()
{
  local tmpdir

  for tmpdir in "$TMPDIR" "$TMP" /tmp /var/tmp "$PWD" ; do
    test -d "$tmpdir" && break
  done

  echo "$tmpdir"
}

###############################################################################

function collect_polynomial_profiles()
{
  # 1. Setup polynomial_root

  local polynomial_root="${1}"
  local raw_profiles="${polynomial_root}/raw_profiles"

  mkdir -p "${raw_profiles}"

  local copyright_holder='Philip Koopman'

  mapfile -d '' cc4_attribution << EOF
The material in this folder is Copyright (c) $(date +%Y) ${copyright_holder}

It is reproduced here under the CC 4.0 International Attribution License:

http://creativecommons.org/licenses/by/4.0/

EOF

  echo "${cc4_attribution}" > "${polynomial_root}/License.txt"

  # 2. Collect profile data
  #

  for (( i=3 ; i<=64 ; i++ )) ; do
    printf -v width "%02d" "$i"

    local -a profile_list=( $(curl --silent "https://users.ece.cmu.edu/~koopman/crc/c${width}"/ \
           | grep -o 'href=".*">' \
           | grep '_len.txt' \
           | sed 's/href="//;s/".*$//') )

    for profile in "${profile_list[@]}" ; do
      curl --silent "https://users.ece.cmu.edu/~koopman/crc/c${width}/${profile}" -o "${raw_profiles}/crc${width}_${profile}"
    done
  done
}

###############################################################################

function convert_hamming_lengths_to_json5()
{
  local lengths_txt="${1}"
  lengths_txt="${lengths_txt#*\{}"
  lengths_txt="${lengths_txt%\}*}"

  local -a lengths_data=( $(echo "${lengths_txt//,/ }") )
  local -i max_hd=$(( ${#lengths_data[@]} + 2 ))

  local -a json5=('[')
  local hd_line
  local json5_comma

  for (( i=0 ; i<=${max_hd} ; i++ )) ; do
    if (( i < ${max_hd} )) ; then
      json5_comma=","
    else
      json5_comma=""
    fi

    if (( i < 2 )) ; then
      hd_line="null${json5_comma} "
    elif (( i == 2 )) ; then
      printf -v hd_line "null${json5_comma}\n"
    else
      mapfile -d '' hd_line << EOF
/* $i */ { "bits"    : ${lengths_data[ $(( i - 3 )) ]}, "bytes"   : $(( ${lengths_data[ $(( i - 3 )) ]} / 8 )) }${json5_comma}
EOF
    fi

    json5+=("$hd_line")
  done

  json5+=(']')

  printf "%s" "${json5[@]}"
}

###############################################################################

function make_polynomial_db()
{
  local polynomial_root="${1}"
  local profiles="${polynomial_root}/profiles"
  local all_polynomials="${SCRIPT_TMPDIR}/all_polynomials.json5"

  mkdir -p "${profiles}"
  mkdir -p "${SCRIPT_TMPDIR}"

  echo "[ " > "$all_polynomials"

  # 1. Convert raw polynomial profile data to JSON5

  while read -r profile_txt ; do
    local profile_path="${profile_txt%/*}"
    local profile_txt_file="${profile_txt##*/}"
    local identity="${profile_txt_file%_len.txt}"
    local identity_crc="${identity%_*}"
    local identity_koopman="${identity#*_}" ; identity_koopman="${identity_koopman/Kx/0x}"
    local profile_json5_file="${identity}_profile.json5"

    echo "Converting \"${profile_txt_file}\" to \"${profile_json5_file}\""

    local -a profile_data
    mapfile -t profile_data < "${profile_txt}"
    local hamming_lengths="${profile_data[-1]}"
    local hamming_lengths_json5=$(convert_hamming_lengths_to_json5 "$hamming_lengths")

    mapfile -d '' profile_json5_data << EOF
{
  "id" : $(${SCRIPT_PATH}/convert_poly k2j ${identity_koopman} | sed -e '$ { /^$/ d}' -e '1 ! s/\(^.*\)/  \1/'),
  "hd" : $(convert_hamming_lengths_to_json5 "$hamming_lengths" | sed -e '$ ! s/\(^.*\)/    \1/' -e '$ s/\(^.*\)/  \1/'),
}
EOF

    echo -n "${profile_json5_data}" > "${profiles}/${profile_json5_file}"
    echo -n "${profile_json5_data}," >> "${all_polynomials}"

  done < <(find "$polynomial_root/raw_profiles" -type f -iname \*_len.txt | sort)

  echo "]" >> "${all_polynomials}"

  # 2. Make a primitive JS polynomial database

  mapfile -d '' polynomial_db << EOF

///////////////////////////////////////////////////////////////////////////////
//
// Database Constructor
//

function Create_PolynomialDatabase(polynomials)
{
  var db = {};

  db.degree = (function extract_polys_by_degree() {
    var degree = []

    for (i = 0 ; i <= 64 ; i++) {
      degree[i] = null;
    }

    for (poly of polynomials) {
      if (degree[poly.id.degree] === null) {
        degree[poly.id.degree] = [ poly ];
      } else {
        degree[poly.id.degree].push(poly);
      }
    }

    return degree;
  })();

  db.HD = (function extract_polys_by_hd() {
    var HD = []

    for (i = 0 ; i <= 32 ; i++) {
      HD[i] = null;
    }

    for (poly of polynomials) {

      for (i = 3 ; i < poly.hd.length ; i++) {
        if (HD[i] === null) {
          HD[i] = [ poly ];
        } else {
          HD[i].push(poly);
        }
      }

    }

    return HD;
  })();

  db.find = function(constraints) {

    if (constraints === null || constraints === undefined || constraints.HD === undefined) {
      constraints = {'HD' : 3, 'len_bytes' : 0, 'degree' : 64}
    }

    if (constraints.len_bytes === undefined) {
      constraints.len_bytes = 0
    }

    if (constraints.degree === undefined) {
      constraints.degree = 64
    }

    var candidates_min_hd = db['HD'][constraints.HD];

    if (candidates_min_hd === undefined || candidates_min_hd === null || candidates_min_hd.length === 0) {
      return null;
    }

    var candidates_min_len_bytes = [];

    for (candidate of candidates_min_hd) {

      if (candidate.hd[constraints.HD].bytes < constraints.len_bytes) {
        continue;
      }

      candidates_min_len_bytes.push(candidate);

    }

    if (candidates_min_len_bytes.length === 0) {
      return null;
    }

    var candidates_final = [];

    var degree_ok;

    if (Array.isArray(constraints.degree)) {
      degree_ok = function(candidate) {
        return constraints.degree.indexOf(candidate.id.degree) !== -1;
      };
    } else {
      degree_ok = function(candidate) {
        return candidate.id.degree <= constraints.degree;
      };
    }

    for (candidate of candidates_min_len_bytes) {

      if (!degree_ok(candidate)) {
        continue;
      }

      candidates_final.push(candidate);

    }

    if (candidates_final.length === 0) {
      return null;
    }

    candidates_final.sort(function predicate(a, b){
      if (a.id.degree != b.id.degree) {
        return a.id.degree - b.id.degree
      }

      var max_common_hd = (a.hd.length < b.hd.length ? a.hd.length : b.hd.length) - 1;

      for (i = constraints.HD ; i <= max_common_hd ; i++) {
        if (a.hd[i].bits == b.hd[i].bits) {
          continue;
        }

        return b.hd[i].bits - a.hd[i].bits;
      }

      return b.hd.length - a.hd.length;
    });

    return candidates_final;
  }

  return db;
}

var polynomials = Create_PolynomialDatabase( $(cat ${all_polynomials}) );

console.log("Try these queries to get you started:\n");
console.log("");
console.log("polynomials.find({'HD' : 6});");
console.log("polynomials.find({'HD' : 6, 'len_bytes' : 1000});");
console.log("polynomials.find({'HD' : 6, 'len_bytes' : 13, 'degree' : 16});");
console.log("polynomials.find({'HD' : 4, 'len_bytes' : 200, 'degree' : 12});");

EOF

  echo -n "${polynomial_db}" > "${polynomial_root}/polynomial_db.js"
}

###############################################################################

function main()
{
  local SCRIPT_PATH=$(realpath "${BASH_SOURCE[0]%/*}")
  local SCRIPT_NAME="${BASH_SOURCE[0]##*/}"
  local REPO_ROOT="$(git rev-parse --show-toplevel)"

  CALLERS_WD="$PWD"

  if [[ "${BASH_SOURCE[0]}" == "${0}" ]] then
    SCRIPT_TMPDIR="$(find_tmp_dir)/${SCRIPT_NAME}"
  else
    SCRIPT_TMPDIR="$(find_tmp_dir)/bash_pid_$$"
  fi

  trap "clean_up ;" EXIT

  # 1. Setup polynomial_root

  local polynomial_root="${1:-${REPO_ROOT}/db/polynomial}"
  local collect_profile_data='No'

  if [[ "${2}" == '-cpd' || "${2}" == '--collect-profile-data' ]] ; then
    collect_profile_data='Yes'
  fi

  # 2. Collect profile data if requested

  if [[ ! -d "$polynomial_root" ]] ; then
    mkdir -p "$polynomial_root"
    collect_profile_data='Yes'
  fi

  if [[ "$collect_profile_data" == 'Yes' ]] ; then
    collect_polynomial_profiles "$polynomial_root"
  fi

  # 3. Convert profile txt data current JSON5 schema
  #    and concantenate the results to form a primitive JS database.

  make_polynomial_db "$polynomial_root"
}

###############################################################################

function clean_up()
{
  rm -rf "$SCRIPT_TMPDIR"
  cd "$CALLERS_WD" &> /dev/null;
}

###############################################################################

main "$@"

