:source-highlighter: rouge
:rouge-style: monokai

= Fast-CRC: User Guide

Fast-CRC provides a standardised and tested library of CRC algorithms.

Fast-CRC is designed to be easy to incorporate into C/C++ applications:

* Download a Fast-CRC release or clone the repository.
* Add Fast-CRC to your build system.
* Copy crc_algorithms.template to somewhere in your application's include tree.
* Rename crc_algorithms.template to crc_algorithms.inc and modify to suit requirements.

== Build system

Fast-CRC ships with cmake files to build a library from the composite source
of crc.c + list(crc_algorithms.inc) included from crc_algorithms.inc.

The key thing is to ensure that there is only one crc_algorithms.inc
visible on the compiler's include path.

== Content of crc_algorithms.inc

Your application specifies the CRC algorithms it requires by including one or more algorithms from the ./crc_algorithms folder.

There is no limit, but be aware that code size is affected.
Choose the smallest number you need for your application.

The crc_algorithms.template provided in the source-root has some examples.

Any algorithm included in the "8-bit Lookup Table" section will generate a 256-element polynomial table and kernel.
The 8-bit tables can be big, eg. a CRC-32 8-bit table takes 1 kB of code space.
They are, however, generally the fastest way of calculating a CRC based on that polynomial.

Any algorithm included in the "4-bit Lookup Table" section will generate a 16-element polynomial table and kernel.
These are a lot smaller than their 8-bit counterparts, eg. a CRC-32 4-bit table takes 64 bytes of code space.
However, this comes at an ~50% speed penalty.

If the required polynomial lookup table and kernel has already been generated, it is used in preference to generating another set.
This means that algorithms in the "4-bit Lookup Table" section can opportunistically use the 8-bit polynomial and kernel -- if available.

The algorithms in the "Fast-CRC" section are bespoke implementations of Gam Ngyen's research described in [1].
Nguyen made detailed analysis on the speed of his algorithms and table-based implementations with respect to the bit-by-bit implementation.
These show that Fast-CRC algorithms typically sit between the 4-bit and 8-bit Lookup Table Implementations in terms of speed.
They have an even smaller footprint than the 4-bit implementations, and can actually outperform the 8-bit implementations (crc16_fast4.inc).

The Nguyen algorithms and polynomials duplicate the functionality of the crc_fast.inc implementations.
Both algorithmic variants are included in the unit tests to demonstrate functional equivalence.

== CRC Interfaces

The CRC interfaces follow a standardised naming convention based on macro expansions in crc_algorithms/interface.h.

For example the interfaces generated by including crc_algorithms/crc16_ccitt.inc:

[source,C]
----

// The "Main Interface" calculates the CRC-16/CCITT CRC across the provided data in a single pass.

uint16_t crc16_CCITT(uint8_t const *data, size_t const data_len);

// The "Accumulation Interface" calculates the CRC-16/CCITT CRC across the provided data in one or more "continue" passes.
// The intermediate crc value returned by _start or _continue is passed into _continue or _finish until the required data is fully processed.

uint16_t crc16_CCITT_start(uint8_t const *data, size_t const data_len);
uint16_t crc16_CCITT_continue(uint16_t const crc, uint8_t const *data, size_t const data_len);
uint16_t crc16_CCITT_finish(uint16_t const crc, uint8_t const *data, size_t const data_len);

----

== References

[1] "Fast CRCs (Extended Version)", Nguyen Gam, https://arxiv.org/pdf/1009.5949.pdf
